### PR TITLE
CSS refactor, adding grunt.js

### PR DESCRIPTION
**Pull request by rogersmj**
# Summary

This pull request offers a cleanup of stylesheet files (as well as how they are organized/handled) and the addition of grunt.js to concatenate and compile SCSS.
# Background

When I first pulled down the project and started to poke around, I had trouble figuring out where to implement style changes because there were some CSS files that weren't being used, and lots of duplication of styles. For example, most of the individual widget styles had been copied out of their individual SCSS files and placed in application.css, rather than allowing the style rules for each widget to remain primarily driven by that widget's individual .scss file. Additionally, the application.scss file seemed to be ignored, in favor of just making direct edits in application.css.
# Goal

To make it easy to add widgets in the future, I wanted to adjust the project so it respected and incorporated each widget's SCSS file. I wanted to reduce duplication of style rules scattered throughout the project, and make it easier to determine where style edits should be made.
# What's changed
1. grunt is now required to compile the CSS for the project. NPM is used to install grunt and dependencies.
2. application.css itself has been removed from the repo. Instead, the project now relies on SCSS files. The grunt tasks (found in Gruntfile.js) search through the project, find all the SCSS files, concatenate them, and then compiles them into a nice big application.css file.
3. The /assets/application.css route in main.py has been changed to reflect the above: that only the application.css file gets loaded when requested by the browser.
4. I went through and individually tweaked styles in a few of the widgets' SCSS files to get them to match more closely the look that the widgets had before I started in on this little CSS-scalping adventure.
# How to test

Pull down this branch and run it according to the updated README. Check that everything still works as before and more or less looks right.

### CODE REVIEW

**Comment by rogersmj** [comment]
Hey @zpriddy, hope you're not offended but I took it upon myself to try to get all the stylesheet handling more organized/DRY. I still have a lot I want to do to make this easier to build on and customize, but I think this is a decent starting point. Let me know if any of the above (or the stuff in the new README file) isn't clear.

Looking forward to collaborating more on this going forward!

**Comment by zpriddy** [comment]
This looks good! I will go check it out tomorrow morning when I am at home and then merge it in. This was something I wanted to do but I wasn't sure how many people were using this and if it was worth the time. I really appreciate it!

I will say that I am not a web developer but more of a back end developer. So it is nice to have someone else help out!

**Comment by zpriddy** [comment]
So I went to go test this an merge it.. I have it on my Mac [This is where i do a lot of my dev work] and I installed grunt.. however when I go to run this I got get any stylesheets.. Can you give me a hand of where to go from here?
screen shot 2015-06-25 at 2 39 29 pm

**Comment by rogersmj** [comment]
Did you also run grunt (not just install it, but run it in the project), and if so what was the result? Did it successfully create application.css?

EDIT: Just to be sure, did you check out the new README and do the npm install and grunt commands from the project root?

I also use a Mac.

**Comment by zpriddy** [comment]
$ grunt
Usage: grunt INPUT_FILE [options]

grunt: error: Input file not provided.

and when I do a npm install.. the first time it listed a lot of things 

npm WARN package.json PyThings@0.1.0 No repository field.
grunt-contrib-concat@0.5.1 node_modules/grunt-contrib-concat
├── source-map@0.3.0 (amdefine@0.1.1)
└── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

grunt-contrib-sass@0.9.2 node_modules/grunt-contrib-sass
├── async@0.9.2
├── dargs@4.0.1 (number-is-nan@1.0.0)
├── cross-spawn@0.2.9 (lru-cache@2.6.4)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── which@1.1.1 (is-absolute@0.1.7)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── lodash@2.4.2
└── gaze@0.5.1 (globule@0.1.0)

grunt@0.4.5 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── getobject@0.1.0
├── eventemitter2@0.4.14
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.7)
├── lodash@0.9.2
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.4)
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-contrib-uglify@0.9.1 node_modules/grunt-contrib-uglify
├── uri-path@0.0.2
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.34, yargs@3.5.4)
├── lodash@3.9.3
└── maxmin@1.1.0 (figures@1.3.5, pretty-bytes@1.0.4, gzip-size@1.0.0)

**Comment by zpriddy** [comment]
But i didn't have node installed.. so that is another thing we will have to add in..

**Comment by rogersmj** [comment]
Correct. NPM (Node Package Manager) is listed in the README as a requirement. So that and grunt have to be installed.

Looks like your `npm install` worked correctly.

What directory are you running `grunt` from? It looks like it's not finding the Gruntfile.js.

**Comment by zpriddy** [comment]
I have tried to run it from all directories but even when I run it as $grunt Gruntfile.js it doesn't create the application.scss

**Comment by rogersmj** [comment]
That's weird. I had another developer pull this down and he didn't have any problems.

What version Grunt do you have? Run `grunt --version`

**Comment by zpriddy** [comment]
zpriddy$ grunt --version
Usage: grunt INPUT_FILE [options]

grunt: error: no such option: --version

**Comment by zpriddy** [comment]
I think I may have other problems then... lol

**Comment by rogersmj** [comment]
Interesting... are you using a virtualenv? Your `npm install` output looks like it did install the latest version of grunt.

What's the output of `which grunt`?

**Comment by zpriddy** [comment]
I just did a nom install.. but i also did a pip install grunt.. that messed things up.. do i fixed that.. then did a npm install -g grunt-cli so that it would be included in the path 
 and now the output is:
grunt
Running "concat:dist" (concat) task
File .compile/build.scss created.

Running "sass:dist" (sass) task

Done, without errors.

grunt --version
grunt-cli v0.1.13
grunt v0.4.5

**Comment by zpriddy** [comment]
it does create a .compile/build.scss but not an application.scss I'm going to try to repeal it and start over

**Comment by rogersmj** [comment]
Hmm. application.scss should already be present in the repo (in the same place as before), so it doesn't need to get created. application.css should be generated by grunt.

I just pulled a fresh copy and ran it; I got the same successful grunt output, and I got the "ZP_PyDash/assets/application.css" file successfully created.

**Comment by zpriddy** [comment]
I just got it to work fine! One of the things I see as a problem is there were a few buttons that I didn't have the right css on and now they show up as just black.. Id like to try to fix those to get them to match. 

(...I think I may have deleted the application.css at some point in time.... ) 

And some of the numbers are no longer the right size.. as well as the % symbol. This ties back to how I did the css in the first version.. and i know it.. 

screen shot 2015-06-26 at 12 15 57 pm

screen shot 2015-06-26 at 12 15 04 pm

**Comment by rogersmj** [comment]
Great! Having grunt and SASS in the project will really help it be easily extensible as more widgets are added.

I see what you're saying about those widgets. I can work on those tonight and try to get them closer to the way they were, before you merge.

**Comment by zpriddy** [comment]
Sounds good. Thank you so much for all of the help on this! :) 
The only other thing I would want to do is add into the ReadMe is the proper way to install npm and grunt - Thats what messed me up - And that npm requires node.

**Comment by rogersmj** [comment]
OK will do!

**Comment by rogersmj** [comment]
OK I think I've gotten the styling more faithful to your original screenshots. Let me know if you spot anything else.

I also added a "watch" task for Grunt that runs by default when you run the "grunt" command, so it will sit there and watch for CSS changes -- and automatically recompile the CSS -- until you kill it.

**Comment by rogersmj** [comment]
And I just updated/reorganized the README a bit so hopefully it's a bit more clear on how to get things running.

**Pull request merged**
